-- CREACION DE DATOS ERRONES Y CORRECTOS
USE TPFI_DDBB;
-- USAMOS DELETE PARA BORRAR TODOS LOS DATOS DE LAS TABLAS Y PODER HACER LAS PRUEBAS

DELETE FROM Empleado;
DELETE FROM Legajo;

-- REINICIA LOS AUTO_INCREMENT A 1 PARA QUE EL NUMERO DE AUTOINCREMENT NO ESTE EN CUALQUIER DATO Y SE REINICIA A 1.
ALTER TABLE Legajo AUTO_INCREMENT = 1;
ALTER TABLE Empleado AUTO_INCREMENT = 1;

INSERT INTO empleado(id,eliminado,nombre,apellido,dni,emial,fechaIngreso,legajo) 
VALUES();